### ISSUE TITLE
GitHub的项目是否可以打标签

### ISSUE THREAD

**Issue by MoncozGC** [utags/utags#13]
很棒的项目！！！
我观察到了GitHub可以对用户进行标签，请问可以适配GitHub的项目也可以打标签嘛。
使用的场景：因为有一些项目是纯英文的，可能会start或者fork下来，但是再下一次去查看的时候会突然想不起来这个项目是干什么的。

**Comment by PipecraftNet** [comment]
好的，尽量下个版本加上这个功能。

**Comment by PipecraftNet** [comment]
@MoncozGC 

刚刚发布了 0.9.3 版本，现在可以对项目 repo 打标签了。欢迎体验，如有需要改善的地方，欢迎留言反馈。

![2023-10-24-14-13-10](https://github.com/utags/utags/assets/88728670/5a585a3e-d3b7-4978-9069-f9cdbf7e8e64)

----

![2023-10-24-14-08-34](https://github.com/utags/utags/assets/88728670/740d5747-ec25-4c42-ac60-63a4afd1d94c)

----

![2023-10-24-14-08-15](https://github.com/utags/utags/assets/88728670/c9024bde-25b2-41ea-afdd-618b7247ddde)

**Comment by MoncozGC** [comment]
👍 好的！！！
