### ISSUE TITLE
新UI的置顶内容可以自定义吗？

### ISSUE THREAD

**Issue by lhj5426** [utags/utags#14]
![image](https://github.com/utags/utags/assets/30548000/8fe9dcad-b510-4d55-a97a-843cdae8618b)
你好大佬 刚才打标签的时候发现 噫 UI更新了 
然后发现左边的置顶都用不到 
就想来问问 这边的指定可以自定义成自己常用的吗？

**Comment by PipecraftNet** [comment]
> 就想来问问 这边的指定可以自定义成自己常用的吗？

当然可以，打开设置就会看到了。
<img width="886" alt="2023-10-20-15-46-49" src="https://github.com/utags/utags/assets/88728670/c7113c3c-02ff-4811-8520-05a2df8f8714">

**Comment by lhj5426** [comment]
原来如此谢谢 设置里
