### ISSUE TITLE
太酷了

### ISSUE THREAD

**Issue by ajavaer** [utags/utags#3]
最近刚好想学习写浏览器扩展程序，就是看语言好像是react写的，vue选手看的有点懵逼

**Comment by PipecraftNet** [comment]
我目前写的几个浏览器扩展/用户脚本都是纯 JS（TypeScript）写的，没有用到 React。因为用到 React 或 Vue，用户脚本的文件大小就太大了，也不想引入外部资源。

这个项目用的脚手架是 https://github.com/utags/browser-extension-starter ，它封装了 [Plasmo](https://www.plasmo.com/)，引入了 esbuild，一套代码可以编译成 Chrome, Firefox 的扩展和用户脚本（油猴脚本）。

如果要写一个浏览器扩展程序并支持编译成用户脚本，那可以看看 https://github.com/utags/browser-extension-starter 。
如果是只是写一个浏览器扩展程序，那可以直接看一下 [Plasmo 的文档](https://docs.plasmo.com/)，它支持 React, Vue, Svelte。

**Comment by ajavaer** [comment]
好的，感谢
