### ISSUE TITLE
Translation Support (requested and offered!)

### ISSUE THREAD

**Issue by Hyperpolymath** [utags/utags#5]
Could you make all the words in the pop up for this in English version too - some are Chinese and others are English (bit strange). I am happy to help with the phrasing of the English form if you like, but I do not know how to change them!

Would be really appreciated - thank you. 

It's a great userscript!

![translation need](https://github.com/utags/utags/assets/6759885/763b6725-5d23-47f4-a472-54b7d2f3c90c)

**Comment by PipecraftNet** [comment]
Sorry for the inconvenience, I should have done the localization earlier.
I'll finish working on the localization module as soon as possible.
Then feel free to contribute translation issues.

BTW, what sites are you using the UTags userscript on and if there are any issues.

**Comment by PipecraftNet** [comment]
Hi, @Hyperpolymath 

The words in the settings popup of the two userscripts (utags and links-helper) have been translated to English now.
If there are any translation issues, please feel free to contribute.

**Comment by Hyperpolymath** [comment]
thank you so much! I really appreciate it. Let me know if there are things at any point that I can help you with!
