### ISSUE TITLE
请问如何取消标签

### ISSUE THREAD

**Issue by ajavaer** [utags/utags#6]
请问如何取消标签。。
我好像取消勾选了也没用

**Comment by PipecraftNet** [comment]
如何删除标签的意思吗？把标签内容清空，然后点击确认即可。

可以参考下面演示

https://github.com/utags/utags/assets/88728670/c57e5540-eba6-4b61-b0ca-8060033a6844

![2023-08-16-23-56-37](https://github.com/utags/utags/assets/88728670/b2477c62-5e91-4769-a7d3-96155ef5a96f)

**Comment by PipecraftNet** [comment]
@ajavaer 如何删除标签的意思吗？把标签内容清空，然后点击确认即可。

可以参考下面演示

https://github.com/utags/utags/assets/88728670/c57e5540-eba6-4b61-b0ca-8060033a6844

![2023-08-16-23-56-37](https://github.com/utags/utags/assets/88728670/b2477c62-5e91-4769-a7d3-96155ef5a96f)

**Comment by ajavaer** [comment]
> @ajavaer* 如何删除标签的意思吗？把标签内容清空，然后点击确认即可。
> 
> 可以参考下面演示
> 
>  2023-08-16-23-56-37.mp4 
> ![2023-08-16-23-56-37](https://user-images.githubusercontent.com/88728670/261067366-b2477c62-5e91-4769-a7d3-96155ef5a96f.gif)

原来是这样，明白了，但是有的时候，没有标签的是否，是否可以保持原来的页面结构。比如推，目前好像不在一行了
![image](https://github.com/utags/utags/assets/31003161/9cd1cd72-c213-443d-9263-2ecfd91380d6)

**Comment by PipecraftNet** [comment]
> 没有标签的是否，是否可以保持原来的页面结构。比如推，目前好像不在一行了

好的，这个下个版本修改。

**Comment by PipecraftNet** [comment]
> 没有标签的是否，是否可以保持原来的页面结构。比如推，目前好像不在一行了

0.8.2 版本修复了 twitter 换行的问题，现在在一行显示了。

<img width="627" alt="2023-08-18-12-25-28" src="https://github.com/utags/utags/assets/88728670/357c1dab-23c2-44a0-9c15-f85e3529d192">

---

<img width="617" alt="2023-08-18-12-27-45" src="https://github.com/utags/utags/assets/88728670/419b9022-2a17-4197-ab79-57acf5d1aed5">

**Comment by ajavaer** [comment]
好的好的，太牛了
