### ISSUE TITLE
youtube上有bug

### ISSUE THREAD

**Issue by mktoky** [utags/utags#7]
youtube上有bug：
1、标签经常错乱。A标签对应A用户，B标签对应B用户，C标签对应C用户。结果A的标签跑到B用户上，B标签跑到C用户上
2、有时候添加标签失败，必须要刷新之后才能添加成功

**Comment by PipecraftNet** [comment]
感谢提供反馈。这个问题我会尽快查找原因并解决。

**Comment by PipecraftNet** [comment]
@mktoky 

> youtube上有bug：
> 1、标签经常错乱。A标签对应A用户，B标签对应B用户，C标签对应C用户。结果A的标签跑到B用户上，B标签跑到C用户上
> 2、有时候添加标签失败，必须要刷新之后才能添加成功

感谢提供这个问题的反馈，这个问题已经解决，已发布 0.8.4 版本。

平时因为使用[🔗 链接助手](https://greasyfork.org/zh-CN/scripts/464541-links-helper)这个油猴脚本，在新窗口打开视频，没有发现这个问题。在原窗口打开视频时，才发现有这个现象。
